"use client";

import { createContext, useCallback, useContext, useMemo, useState } from "react";

type DemoSyncValue = {
  activeLabel:    string;
  inlinePlaying:  boolean;
  inlineProgress: number;
  /** Noise bars generated by DemoPlayer - shared with AudioDemoPlayer */
  inlineBars:     number[];
  setInlineDemo:  (playing: boolean, label: string, progress: number) => void;
  setInlineBars:  (bars: number[]) => void;
  resetInlineDemo: () => void;
};

const DemoSyncContext = createContext<DemoSyncValue | null>(null);

const DEFAULT_BARS = Array(64).fill(5);

export function DemoSyncProvider({ children }: { children: React.ReactNode }) {
  const [activeLabel,    setActiveLabel]    = useState("");
  const [inlinePlaying,  setInlinePlaying]  = useState(false);
  const [inlineProgress, setInlineProgress] = useState(0);
  const [inlineBars,     setInlineBars]     = useState<number[]>(DEFAULT_BARS);

  const setInlineDemo = useCallback((playing: boolean, label: string, progress: number) => {
    setInlinePlaying(playing);
    setActiveLabel(label);
    setInlineProgress(progress);
  }, []);

  const resetInlineDemo = useCallback(() => {
    setInlinePlaying(false);
    setActiveLabel("");
    setInlineProgress(0);
    setInlineBars(DEFAULT_BARS);
  }, []);

  const value = useMemo(() => ({
    activeLabel, inlinePlaying, inlineProgress, inlineBars,
    setInlineDemo, setInlineBars, resetInlineDemo,
  }), [activeLabel, inlinePlaying, inlineProgress, inlineBars, setInlineDemo, setInlineBars, resetInlineDemo]);

  return <DemoSyncContext.Provider value={value}>{children}</DemoSyncContext.Provider>;
}

export function useDemoSync() {
  const ctx = useContext(DemoSyncContext);
  if (!ctx) throw new Error("useDemoSync must be used within DemoSyncProvider");
  return ctx;
}
