export const TERMS_AND_CONDITIONS_META = {
  eyebrow: "Legal",
  title: "Terms & Conditions",
  intro:
    "Welcome to OnDial.ai. By accessing or using our website, products, and services, you agree to comply with and be bound by the following Terms and Conditions. Please read them carefully before using our platform.",
} as const;

export type TermsAndConditionsSection = {
  id: string;
  title: string;
  paragraphs?: readonly string[];
  lead?: string;
  bullets?: readonly string[];
  footer?: string;
};

export const TERMS_AND_CONDITIONS_SECTIONS: readonly TermsAndConditionsSection[] = [
  {
    id: "acceptance",
    title: "Acceptance of Terms",
    paragraphs: [
      "By using OnDial.ai, you confirm that you are at least 18 years old (or have parental/guardian consent) and have the legal capacity to enter into these Terms. If you do not agree, you must stop using our services immediately.",
    ],
  },
  {
    id: "services",
    title: "Services Provided",
    bullets: [
      "OnDial.ai offers AI-powered tools, digital solutions, and related services designed to enhance business communication, automation, and productivity.",
      "We reserve the right to modify, improve, or discontinue any part of our services at any time.",
      "Results generated by AI are for informational purposes only and should not be considered professional, legal, medical, or financial advice.",
    ],
  },
  {
    id: "user-responsibilities",
    title: "User Responsibilities",
    lead: "By using our platform, you agree that you will:",
    bullets: [
      "Use the website only for lawful purposes.",
      "Not engage in activities that may harm, disrupt, or misuse our platform.",
      "Provide accurate information during registration and keep your account credentials secure.",
      "You are solely responsible for all content and actions taken under your account.",
    ],
  },
  {
    id: "intellectual-property",
    title: "Intellectual Property Rights",
    bullets: [
      "All content, trademarks, logos, and software on OnDial.ai are owned or licensed by us.",
      "You may not copy, reproduce, distribute, or modify our content without prior written consent.",
      "Any feedback or suggestions you provide may be used by us without obligation to compensate you.",
    ],
  },
  {
    id: "payments",
    title: "Payments & Subscriptions",
    bullets: [
      "Certain features or services may require payment or subscription.",
      "By purchasing, you agree to provide accurate billing details and authorize us to charge applicable fees.",
      "Subscription renewals will be processed automatically unless canceled prior to the renewal date.",
    ],
  },
  {
    id: "disclaimer",
    title: "Disclaimer of Warranties",
    bullets: [
      'Our services are provided "as is" and "as available" without warranties of any kind.',
      "We do not guarantee uninterrupted, error-free, or fully accurate outputs from our AI tools.",
      "OnDial.ai is not liable for any decisions made based on AI-generated content.",
    ],
  },
  {
    id: "limitation-of-liability",
    title: "Limitation of Liability",
    lead: "To the fullest extent permitted by law:",
    bullets: [
      "OnDial.ai shall not be held responsible for any indirect, incidental, or consequential damages.",
      "Our total liability for any claim shall not exceed the amount paid by you (if any) for using our services.",
    ],
  },
  {
    id: "third-party",
    title: "Third-Party Services",
    paragraphs: [
      "Our platform may integrate with or link to third-party websites and services. We are not responsible for their content, policies, or practices.",
    ],
  },
  {
    id: "termination",
    title: "Termination of Use",
    lead: "We reserve the right to suspend or terminate your account if you:",
    bullets: [
      "Violate these Terms & Conditions",
      "Engage in fraudulent, abusive, or illegal activities",
      "Misuse or exploit our services",
    ],
  },
  {
    id: "changes",
    title: "Changes to Terms",
    paragraphs: [
      'We may update these Terms from time to time to reflect changes in our services, legal requirements, or policies. Updates will be posted on this page with a revised "Last Updated" date. Continued use of OnDial.ai after changes means you accept the updated Terms.',
    ],
  },
] as const;

export const TERMS_AND_CONDITIONS_CONTACT = {
  title: "Contact Us",
  description: "For any questions about these Terms & Conditions, please contact us:",
  email: "contact@ondial.ai",
  website: "https://ondial.ai",
  websiteLabel: "ondial.ai",
} as const;
